### ISSUE TITLE
Report checklist

### ISSUE THREAD

**Issue by rafflesandrison** [cs2102team20/cs2102team20-crowd-funding-frontend#47]
Project report (up to a maximum of 20 pages in PDF format with at least 10-point font size). The report should include the following.

- [x] Names and student numbers of all team members (that start with A instead of E), project team number, and project topic (on the first page).
- [x] A listing of the project responsibilities of each team member.
- [x] A description of your application’s requirements and functionalities.
- - [x] Highlight any interesting/non-trivial aspects of your application’s functionalities/implementation.
- - [x] Describe and explain all constraints in your application.
- [x] The ER model of your application (which must satisfy the requirements in Section 2). If your ER model is too large (spanning more than a page), you may want to either (a) include a single-page simplified ER model with non-key attributes omitted, or (b) explain your ER model piece-wise such as for every relation set and entity sets connected to the relation set. You can then present the more detailed ER model.
- [x] The relational schema derived from your ER data model; i.e., show the DDL statements of all your database tables.
- If there is any table that is not in 3NF/BCNF, justify your design decision.
- If all your tables are in 3NF/BCNF, briefly explain.
- [x]  An English description of each of the three non-trivial constraints that are enforced using triggers. Show the code of your trigger implementation.
- [x]  Specification of the software tools/frameworks used in your project.
- [x]  Two or three representative screenshots of your application in action.
